version: '2'

volumes:
    timtec_database_data: {}

services:
    timtec_database:
        container_name: timtec_database
        image: postgres:9.5
        restart: always
        volumes:
            - timtec_database_data:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=timtec
            - POSTGRES_USER=timtec

    timtec_django:
        container_name: timtec_django
        command: python /app/timtec/manage.py runserver 0.0.0.0:8000
        restart: always
        build:
            context: .
            dockerfile: Dockerfile-dev
        volumes:
            - .:/app/timtec
            - ../timtec-theme-if:/app/timtec-theme-if
            - ../timtec-theme-timtec:/app/timtec-theme-timtec
        links:
            - timtec_database:database
        ports:
            - "0.0.0.0:8000:8000"
